spring:
  datasource:
    url: jdbc:postgresql://${AGROFARM_DB_HOST:localhost}:${AGROFARM_DB_PORT:5433}/${AGROFARM_DB:agrofarm_db}
    username: ${AGROFARM_USER:agrofarm_user}
    password: ${AGROFARM_PASSWORD:agrofarm_password}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog.xml

logging:
  file:
    path: ./logs

application:
  security:
    jwt:
      secret-key: 4309ujf034m093k4c0943j80n89cn4389n0348cni3nc3c
      access-token-expiration-time: 3600000
      refresh-token-expiration-time: 43200000

gemini:
  api:
    key: AIzaSyBKgNgruSWtW_Lo5-in3civoEnSqcbN_d8
    temperature: 0.9
    topK: 1
    topP: 1
    maxOutputTokens: 2048
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent?key=

vertex:
  projectId: logical-iridium-424814-e7
  location: asia-northeast3
  modelName: gemini-1.0-pro-vision
