create table roles
(
    id   bigint generated by default as identity not null,
    name varchar not null,
    constraint pk_roles primary key (id)
);

create table users
(
    id           bigint generated by default as identity not null,
    name         varchar,
    lastname     varchar,
    birthday     date,
    phone_number varchar,
    email        varchar,
    password     varchar,
    created_at   timestamp,
    updated_at   timestamp,
    constraint pk_users primary key (id)
);

create table user_roles
(
    user_id bigint,
    role_id bigint
);

alter table user_roles
    add constraint fk_user_roles_on_roles foreign key (role_id) references roles (id);

alter table user_roles
    add constraint fk_user_roles_on_users foreign key (user_id) references users (id);